### ISSUE TITLE
BagDataset Shape mismatch with BagNet model

### ISSUE THREAD

**Issue by jerofad** [AgenoDrei/pad_classification#1]
hey simon thanks for sharing your work. I am trying to make use of your retina bag dataset code here
https://github.com/AgenoDrei/pad_classification/blob/566f46f9dfa764a8c867638962366710f88945bd/include/nn_datasets.py#L122
however, this line of code here results into having 5 dimensions i.e based on the `torch.stack`. So we would arrive at `(bs, x, 3, 399, 399)` where x is the number of frames in the stack. 

But then, the model here
https://github.com/AgenoDrei/pad_classification/blob/566f46f9dfa764a8c867638962366710f88945bd/include/nn_models.py#L65
is expecting a 4 dimensional input considering we're using a CNN pretrained model. 
I'm I missing something here? or whats the work-around this?

TIA

**Comment by AgenoDrei** [comment]
Hey,

in this case I am cheating a bit. I am using a batch size of 1 and instead load the different frames into the batch size dimension of the input tensor. This way I can create features from the different sub-images in parallel using the same extractor. 

Does this make sense? 

Kind regards

**Comment by jerofad** [comment]
Hey, thank for your response.

Oh so in that case, the sub-images serve as the "batch size".  Got it.

Let me get to work on this and see if I can run the code with this new information.

Thanks
